version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/twilio-video-react-app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
    
      - run: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: "Jest Unit Tests"
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "test-reports/jest"
            JEST_JUNIT_OUTPUT_NAME: "results.xml"
            JEST_JUNIT_CLASSNAME: "{classname}"
            JEST_JUNIT_TITLE: "{title}"

      - store_artifacts:
          path: coverage

      - run: 
          name: "Build app with Firebase auth disabled"
          command: npm run build
          environment:
            REACT_APP_TOKEN_ENDPOINT: "http://localhost:8081/token"

      - run: 
          name: "Set environment variables for local token server (used by Cypress tests)"
          command: |
            echo TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID >> .env
            echo TWILIO_API_KEY_SID=$TWILIO_API_KEY >> .env
            echo TWILIO_API_KEY_SECRET=$TWILIO_API_SECRET >> .env

      - run: npm run cypress:ci

      - store_test_results:
          path: test-reports

      # Rebuild app with firebase auth enabled
      - run:
          name: "Build app with Firebase auth enabled"
          command: |
            echo REACT_APP_SET_AUTH=firebase >> .env
            echo REACT_APP_TOKEN_ENDPOINT=$REACT_APP_TOKEN_ENDPOINT >> .env
            echo REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY >> .env
            echo REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN >> .env
            echo REACT_APP_FIREBASE_DATABASE_URL=$REACT_APP_FIREBASE_DATABASE_URL >> .env
            echo REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET >> .env
            echo REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID >> .env
            echo REACT_APP_GIT_TAG=$CIRCLE_TAG >> .env
            echo REACT_APP_GIT_COMMIT=$CIRCLE_SHA1 >> .env
            npm run build

      - persist_to_workspace:
          root: .
          paths: 
            - .

  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/twilio-video-react-app

    steps:
      - attach_workspace:
          at: ~/twilio-video-react-app
     
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run: echo $CIRCLE_TAG > build/version.txt

      - run: gcloud app deploy -q

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/